-- Script para criar todas as bases ausentes que estão sendo referenciadas
-- Este script resolve completamente os erros de foreign key constraint

-- Inserir todas as bases ausentes baseadas nos dados do project_bases
INSERT INTO bases (id, name, location, active, created_at) VALUES
    (6, 'MI03 ALPHAVILLE', 'Alphaville, SP', true, NOW()),
    (7, 'MI04 BARUERI', 'Barueri, SP', true, NOW()),
    (42, 'FMS09 SAO PAULO SP', 'São Paulo, SP', true, NOW()),
    (43, 'PTL01 BELEM (PETLOVE)', 'Belém, PA', true, NOW()),
    (44, 'PTL02 JUNDIA (PETLOVE)', 'Jundiaí, SP', true, NOW()),
    (45, 'PB01 FABRICA PRIMO BASILE', 'Primo Basile', true, NOW()),
    (46, 'LH01 LINE HALL', 'Line Hall', true, NOW()),
    (47, 'COCA COLA (ABC)', 'ABC, SP', true, NOW()),
    (48, 'COCA COLA (APARECIDA)', 'Aparecida, SP', true, NOW()),
    (49, 'COCA COLA (CRICIUMA)', 'Criciúma, SC', true, NOW()),
    (50, 'COCA COLA (IPATINGA)', 'Ipatinga, MG', true, NOW()),
    (51, 'COCA COLA (JURUBATUBA)', 'Jurubatuba, SP', true, NOW()),
    (52, 'COCA COLA (MARIANA)', 'Mariana, MG', true, NOW()),
    (53, 'COCA COLA (PINHEIROS)', 'Pinheiros, SP', true, NOW()),
    (54, 'COCA COLA (PONTE NOVA)', 'Ponte Nova, MG', true, NOW()),
    (55, 'COCA COLA SANTOS', 'Santos, SP', true, NOW()),
    (57, 'MM01 (CAJAMAR)', 'Cajamar, SP', true, NOW()),
    (58, 'MM03 (ARUJA)', 'Arujá, SP', true, NOW()),
    (59, 'MM04 (JUNDIAI)', 'Jundiaí, SP', true, NOW()),
    (60, 'OXXO1 (CAJAMAR)', 'Cajamar, SP', true, NOW()),
    (63, 'FMS09 SÃO PAULO (SP)', 'São Paulo, SP', true, NOW()),
    (67, 'PTL05 BELEM (SEMANAL)', 'Belém, PA', true, NOW()),
    (68, 'MM05 (OSASCO)', 'Osasco, SP', true, NOW()),
    (69, 'SC (ABC) SSP17', 'ABC, SP', true, NOW()),
    (70, 'SC (ARACATUBA) SSP10', 'Araçatuba, SP', true, NOW()),
    (71, 'SC (ARENA BARUERI) SSP5', 'Barueri, SP', true, NOW()),
    (72, 'SC (ATIBAIA) SSP25', 'Atibaia, SP', true, NOW()),
    (73, 'SC (AVARÉ) SSP24', 'Avaré, SP', true, NOW()),
    (74, 'SC (BAHIA SALVADOR) SBA1', 'Salvador, BA', true, NOW()),
    (75, 'SC (BAURU) SSP14', 'Bauru, SP', true, NOW()),
    (79, 'SC (CAMPINAS S3) SSP3', 'Campinas, SP', true, NOW()),
    (80, 'SC (CAMPINAS S7) SSP37', 'Campinas, SP', true, NOW()),
    (81, 'SC (CAMPO GRANDE) SMS1', 'Campo Grande, MS', true, NOW()),
    (82, 'SC (CARAGUATATUBA) SSP16', 'Caraguatatuba, SP', true, NOW()),
    (83, 'SC (CASCAVEL) SPR3', 'Cascavel, PR', true, NOW()),
    (84, 'SC (CHAPECÓ) SSC4', 'Chapecó, SC', true, NOW()),
    (85, 'SC (CONTAGEM) SMG1', 'Contagem, MG', true, NOW()),
    (86, 'SC (COTIA) SSP34', 'Cotia, SP', true, NOW()),
    (87, 'SC (CRICIÚMA) SSC5-SDD', 'Criciúma, SC', true, NOW()),
    (88, 'SC (CUIABÁ) SMR1', 'Cuiabá, MT', true, NOW()),
    (89, 'SC (CURITIBA) SPR1', 'Curitiba, PR', true, NOW()),
    (90, 'SC (DIVINÓPOLIS) SMG10', 'Divinópolis, MG', true, NOW()),
    (91, 'SC (FLORIANÓPOLIS) SSC2', 'Florianópolis, SC', true, NOW()),
    (92, 'SC (FORTALEZA) SCE1', 'Fortaleza, CE', true, NOW()),
    (93, 'SC (FRANCA) SSP26', 'Franca, SP', true, NOW()),
    (94, 'SC (FULL FILMENTE) FULL', 'Filial Plena', true, NOW()),
    (95, 'SC (GOIÂNIA) SGO1', 'Goiânia, GO', true, NOW()),
    (96, 'SC (GUARAPUAVA) SPR5', 'Guarapuava, PR', true, NOW()),
    (97, 'SC (ITAPETININGA) SSP27', 'Itapetininga, SP', true, NOW()),
    (98, 'SC (ITAQUERA) SSP45', 'Itaquera, SP', true, NOW()),
    (99, 'SC (ITUPEVA) SSP38-SDD', 'Itupeva, SP', true, NOW()),
    (100, 'SC (JALES) SSP28', 'Jales, SP', true, NOW()),
    (101, 'SC (JOINVILLE) SSC1', 'Joinville, SC', true, NOW()),
    (102, 'SC (LAJEADO) SRS10-SDD', 'Lajeado, RS', true, NOW()),
    (103, 'SC (LONDRINA) SPR2', 'Londrina, PR', true, NOW()),
    (104, 'SC (MANAUS) SAM1', 'Manaus, AM', true, NOW()),
    (105, 'SC (MARÍLIA) SSP13', 'Marília, SP', true, NOW()),
    (106, 'SC (MARINGÁ) SPR6', 'Maringá, PR', true, NOW()),
    (107, 'SC (MEGA GUARULHOS) SSP30', 'Guarulhos, SP', true, NOW()),
    (108, 'SC (MOGI DAS CRUZES) SSP23', 'Mogi das Cruzes, SP', true, NOW()),
    (109, 'SC (MOOCA CENTRO) SSP21', 'Mooca, SP', true, NOW()),
    (110, 'SC (PASSO FUNDO) SRS5-SDD', 'Passo Fundo, RS', true, NOW()),
    (111, 'SC (PATO BRANCO) SPR4', 'Pato Branco, PR', true, NOW()),
    (112, 'SC (PATOS MINAS) SMG11-SDD', 'Patos de Minas, MG', true, NOW()),
    (113, 'SC (PELOTAS) SRS2', 'Pelotas, RS', true, NOW()),
    (114, 'SC (PIRACICABA) SSP36', 'Piracicaba, SP', true, NOW()),
    (115, 'SC (POÇOS DE CALDAS) SMG5', 'Poços de Caldas, MG', true, NOW()),
    (116, 'SC (PONTA GROSSA) SPR7', 'Ponta Grossa, PR', true, NOW()),
    (117, 'SC (PORTO ALEGRE) SRS1', 'Porto Alegre, RS', true, NOW()),
    (118, 'SC (PQ NOVO MUNDO) SSP40', 'Parque Novo Mundo, SP', true, NOW()),
    (119, 'SC (PRESIDENTE PRUDENTE) SSP11', 'Presidente Prudente, SP', true, NOW()),
    (120, 'SC (QUEIMADOS) SRJ2', 'Queimados, RJ', true, NOW()),
    (121, 'SC (RECIFE) SPE1', 'Recife, PE', true, NOW()),
    (122, 'SC (RIBEIRÃO PRETO) SSP4', 'Ribeirão Preto, SP', true, NOW()),
    (123, 'SC (SANTA MARIA) SRS3', 'Santa Maria, RS', true, NOW()),
    (124, 'SC (SANTOS) SSP15-SDD', 'Santos, SP', true, NOW()),
    (125, 'SC (SÃO CARLOS) SSP22', 'São Carlos, SP', true, NOW()),
    (126, 'SC (SÃO JOSÉ DOS CAMPOS) SSP8', 'São José dos Campos, SP', true, NOW()),
    (127, 'SC (SAPUCAIA) SRS8', 'Sapucaia do Sul, RS', true, NOW()),
    (128, 'SC (SJ RIO PRETO) SSP12', 'São José do Rio Preto, SP', true, NOW()),
    (129, 'SC (SOROCABA) SSP20', 'Sorocaba, SP', true, NOW()),
    (130, 'SC (VITÓRIA) SES1-SDD', 'Vitória, ES', true, NOW()),
    (131, 'SC (Z LESTE) SSP6', 'Zona Leste, SP', true, NOW()),
    (132, 'SC (Z SUL) SC_ZS', 'Zona Sul, SP', true, NOW()),
    (133, 'XPT (ALTA FLORESTA) EMR5/SMR2', 'Alta Floresta, MT', true, NOW()),
    (134, 'XPT (AMERICANA/POLIS) ESP12/SSP17', 'Americana, SP', true, NOW()),
    (135, 'XPT (BRASÍLIA) ESP13/SPSP5', 'Brasília, DF', true, NOW()),
    (136, 'XPT (CHAPADINHA) EMN3/SMN1', 'Chapadinha, MA', true, NOW()),
    (137, 'XPT (ERECHIM) ERS6/SRS5', 'Erechim, RS', true, NOW()),
    (138, 'XPT (FRANCISCO BELTRÃO) ERP9/SPR4', 'Francisco Beltrão, PR', true, NOW()),
    (139, 'XPT (MANOEL RIBAS) EPR13/SPR5', 'Manoel Ribas, PR', true, NOW()),
    (140, 'XPT (SANTO ANTONIO DA PLATINA) EPR7/SPR2', 'Santo Antônio da Platina, PR', true, NOW()),
    (141, 'XPT (SÃO MATEUS DO SUL) ERP6/SPR7', 'São Mateus do Sul, PR', true, NOW()),
    (142, 'XPT (TRÊS LAGOAS) EM54/SSP10', 'Três Lagoas, MS', true, NOW()),
    (143, 'XPT (UMUARAMA) EPR8/SPR6', 'Umuarama, PR', true, NOW()),
    (144, 'XPT (VIÇOSA) EMG15/SRJ12', 'Viçosa, MG', true, NOW()),
    (145, 'FULL MELI (FMELI01)', 'Mercado Livre', true, NOW()),
    (146, 'Base Manutenção', 'Manutenção Geral', true, NOW()),
    (147, 'Base Uso Operacional', 'Uso Operacional', true, NOW()),
    (148, 'Line Hall Shopee', 'Line Hall Shopee', true, NOW())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    location = EXCLUDED.location,
    active = true;

-- Atualizar a sequência da tabela bases para evitar conflitos futuros
SELECT setval('bases_id_seq', (SELECT COALESCE(MAX(id), 150) FROM bases), true);

-- Verificar o resultado
SELECT 'Bases criadas com sucesso. Total de bases:' as status, COUNT(*) as total FROM bases;
SELECT 'Verificação de integridade - projetos com base_id inválidos (deve ser 0):' as status, COUNT(*) as invalid_count
FROM project_bases pb
WHERE pb.id NOT IN (SELECT id FROM bases);