-- Script para criar as tabelas da Base Campinas no Supabase
-- Este script cria todas as tabelas necessárias para o módulo de Base Campinas:
-- 1. campinas_budget_requests (Solicitações de orçamento)
-- 2. campinas_expenses (Despesas)
-- 3. campinas_tire_requests (Solicitações de pneus)
-- 4. campinas_fleet_maintenance (Manutenção de frota)

-- 1. Tabela para solicitações de orçamento da Base Campinas
CREATE TABLE IF NOT EXISTS campinas_budget_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  priority VARCHAR(50) NOT NULL CHECK (priority IN ('baixa', 'média', 'alta')),
  status VARCHAR(50) NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente', 'aprovado', 'rejeitado')),
  requester_id INTEGER NOT NULL,
  requester_name VARCHAR(255) NOT NULL,
  estimated_value DECIMAL(10, 2) NOT NULL,
  department VARCHAR(100) NOT NULL,
  approved_value DECIMAL(10, 2),
  approved_by VARCHAR(255),
  approved_at TIMESTAMP WITH TIME ZONE,
  comments TEXT,
  budget_file_url TEXT,
  budget_file_name VARCHAR(255),
  invoice_file_url TEXT,
  invoice_file_name VARCHAR(255),
  pending_invoice BOOLEAN DEFAULT FALSE,
  base_id INTEGER DEFAULT 2,
  base_name VARCHAR(100) DEFAULT 'Base Campinas',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Índices para a tabela de solicitações de orçamento
CREATE INDEX IF NOT EXISTS idx_campinas_budget_status ON campinas_budget_requests(status);
CREATE INDEX IF NOT EXISTS idx_campinas_budget_requester ON campinas_budget_requests(requester_id);
CREATE INDEX IF NOT EXISTS idx_campinas_budget_department ON campinas_budget_requests(department);
CREATE INDEX IF NOT EXISTS idx_campinas_budget_created_at ON campinas_budget_requests(created_at);

-- 2. Tabela para despesas da Base Campinas
CREATE TABLE IF NOT EXISTS campinas_expenses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  category VARCHAR(100) NOT NULL,
  amount DECIMAL(10, 2) NOT NULL,
  due_date DATE,
  payment_date DATE,
  status VARCHAR(50) NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente', 'pago', 'atrasado', 'cancelado')),
  description TEXT,
  receipt_url TEXT,
  receipt_file_name VARCHAR(255),
  recurring BOOLEAN DEFAULT FALSE,
  recurrence_frequency VARCHAR(50),
  requester_id INTEGER NOT NULL,
  requester_name VARCHAR(255) NOT NULL,
  approved_by VARCHAR(255),
  approved_at TIMESTAMP WITH TIME ZONE,
  base_id INTEGER DEFAULT 2,
  base_name VARCHAR(100) DEFAULT 'Base Campinas',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Índices para a tabela de despesas
CREATE INDEX IF NOT EXISTS idx_campinas_expenses_category ON campinas_expenses(category);
CREATE INDEX IF NOT EXISTS idx_campinas_expenses_status ON campinas_expenses(status);
CREATE INDEX IF NOT EXISTS idx_campinas_expenses_due_date ON campinas_expenses(due_date);
CREATE INDEX IF NOT EXISTS idx_campinas_expenses_requester ON campinas_expenses(requester_id);

-- 3. Tabela para solicitações de pneus da Base Campinas
CREATE TABLE IF NOT EXISTS campinas_tire_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quantity INTEGER NOT NULL,
  tire_size VARCHAR(100) NOT NULL,
  tire_model VARCHAR(100),
  priority VARCHAR(50) NOT NULL CHECK (priority IN ('baixa', 'média', 'alta')),
  status VARCHAR(50) NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente', 'aprovado', 'rejeitado', 'entregue')),
  vehicle_plate VARCHAR(10),
  reason TEXT NOT NULL,
  requester_id INTEGER NOT NULL,
  requester_name VARCHAR(255) NOT NULL,
  approved_by VARCHAR(255),
  approved_at TIMESTAMP WITH TIME ZONE,
  delivery_date DATE,
  comments TEXT,
  base_id INTEGER DEFAULT 2,
  base_name VARCHAR(100) DEFAULT 'Base Campinas',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Índices para a tabela de solicitações de pneus
CREATE INDEX IF NOT EXISTS idx_campinas_tire_status ON campinas_tire_requests(status);
CREATE INDEX IF NOT EXISTS idx_campinas_tire_vehicle ON campinas_tire_requests(vehicle_plate);
CREATE INDEX IF NOT EXISTS idx_campinas_tire_requester ON campinas_tire_requests(requester_id);

-- 4. Tabela para manutenção de frota da Base Campinas
CREATE TABLE IF NOT EXISTS campinas_fleet_maintenance (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_plate VARCHAR(10) NOT NULL,
  vehicle_model VARCHAR(100) NOT NULL,
  maintenance_type VARCHAR(100) NOT NULL,
  description TEXT NOT NULL,
  priority VARCHAR(50) NOT NULL CHECK (priority IN ('baixa', 'média', 'alta')),
  status VARCHAR(50) NOT NULL DEFAULT 'pendente' CHECK (status IN (
    'pendente', 'em_andamento', 'aguardando_pecas', 
    'aguardando_orcamento', 'orcamento_aprovado', 
    'em_negociacao', 'concluida', 'cancelada'
  )),
  start_date DATE,
  end_date DATE,
  estimated_cost DECIMAL(10, 2),
  final_cost DECIMAL(10, 2),
  workshop_id INTEGER,
  workshop_name VARCHAR(255),
  responsible_person VARCHAR(255),
  approver_name VARCHAR(255),
  approved_at TIMESTAMP WITH TIME ZONE,
  km_atual INTEGER,
  prazo_estimado VARCHAR(100),
  descricao_servico TEXT,
  maintenance_chat_id INTEGER,
  requester_id INTEGER NOT NULL,
  requester_name VARCHAR(255) NOT NULL,
  base_id INTEGER DEFAULT 2,
  base_name VARCHAR(100) DEFAULT 'Base Campinas',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Índices para a tabela de manutenção de frota
CREATE INDEX IF NOT EXISTS idx_campinas_maintenance_vehicle ON campinas_fleet_maintenance(vehicle_plate);
CREATE INDEX IF NOT EXISTS idx_campinas_maintenance_status ON campinas_fleet_maintenance(status);
CREATE INDEX IF NOT EXISTS idx_campinas_maintenance_workshop ON campinas_fleet_maintenance(workshop_id);
CREATE INDEX IF NOT EXISTS idx_campinas_maintenance_requester ON campinas_fleet_maintenance(requester_id);

-- Trigger para atualizar o campo updated_at quando um registro é alterado

-- Função para atualizar o timestamp
CREATE OR REPLACE FUNCTION update_timestamp_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = CURRENT_TIMESTAMP;
   RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger para cada tabela
CREATE TRIGGER update_campinas_budget_timestamp
BEFORE UPDATE ON campinas_budget_requests
FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();

CREATE TRIGGER update_campinas_expenses_timestamp
BEFORE UPDATE ON campinas_expenses
FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();

CREATE TRIGGER update_campinas_tire_timestamp
BEFORE UPDATE ON campinas_tire_requests
FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();

CREATE TRIGGER update_campinas_maintenance_timestamp
BEFORE UPDATE ON campinas_fleet_maintenance
FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();

-- Views para relatórios

-- View para estatísticas de solicitações de orçamento
CREATE VIEW campinas_budget_stats AS
SELECT 
  status,
  COUNT(*) as total_count,
  SUM(estimated_value) as total_estimated,
  SUM(CASE WHEN approved_value IS NOT NULL THEN approved_value ELSE 0 END) as total_approved,
  EXTRACT(MONTH FROM created_at) as month,
  EXTRACT(YEAR FROM created_at) as year
FROM campinas_budget_requests
GROUP BY status, month, year;

-- View para estatísticas de despesas
CREATE VIEW campinas_expenses_stats AS
SELECT 
  category,
  status,
  COUNT(*) as total_count,
  SUM(amount) as total_amount,
  EXTRACT(MONTH FROM due_date) as month,
  EXTRACT(YEAR FROM due_date) as year
FROM campinas_expenses
GROUP BY category, status, month, year;

-- View para estatísticas de solicitações de pneus
CREATE VIEW campinas_tire_stats AS
SELECT 
  status,
  COUNT(*) as total_count,
  SUM(quantity) as total_quantity,
  tire_size,
  EXTRACT(MONTH FROM created_at) as month,
  EXTRACT(YEAR FROM created_at) as year
FROM campinas_tire_requests
GROUP BY status, tire_size, month, year;

-- View para estatísticas de manutenção de frota
CREATE VIEW campinas_maintenance_stats AS
SELECT 
  status,
  maintenance_type,
  COUNT(*) as total_count,
  SUM(CASE WHEN estimated_cost IS NOT NULL THEN estimated_cost ELSE 0 END) as total_estimated,
  SUM(CASE WHEN final_cost IS NOT NULL THEN final_cost ELSE 0 END) as total_final,
  EXTRACT(MONTH FROM created_at) as month,
  EXTRACT(YEAR FROM created_at) as year
FROM campinas_fleet_maintenance
GROUP BY status, maintenance_type, month, year;