-- Inserir todas as rotas reais do Line Hall Shopee
INSERT INTO line_hall_routes (nome_ponto_a, nome_ponto_b, km_total) VALUES
('Araçatuba SP', 'São Paulo SP', 1074),
('Maringá PR', 'São Paulo SP', 648),
('Cravinhos SP', 'Aparecida GO', 606),
('Hidrolândia GO', 'Cravinhos SP', 603),
('Curitiba PR', 'São João de Meriti RJ', 961),
('Santana de Parnaíba SP', 'Curitiba PR', 411),
('Cravinhos SP', 'Marília SP', 290),
('Maringá PR', 'Cravinhos SP', 576),
('Artur Alvim SP', 'São João de Meriti RJ', 537),
('Louveira SP', 'Hidrolândia GO', 800),
('Guarulhos SP', 'Cravinhos SP', 313),
('Aparecida GO', 'Cravinhos SP', 615),
('Curitiba PR', 'Guarapuava', 254),
('Louveira SP', 'Maringá PR', 641),
('Aparecida GO', 'São José do Rio Preto SP', 504),
('Aparecida GO', 'São Paulo SP', 895),
('Curitiba PR', 'Toledo', 540),
('Cravinhos SP', 'São José do Rio Preto SP', 225),
('Artur Alvim SP', 'Rio de Janeiro RJ', 429),
('Maringá PR', 'Santana de Parnaíba SP', 614),
('Louveira SP', 'Aparecida de Goiânia', 618),
('Campo Grande RJ', 'Guarulhos SP', 380),
('São Paulo SP', 'SC Joinville × SP Franco da Rocha', 520),
('Louveira SP', 'Cravinhos SP', 224),
('Guarulhos SP', 'Louveira SP', 120),
('Cascavel PR', 'Guarulhos SP', 980),
('São Carlos SP', 'Louveira SP', 406),
('Cravinhos SP', 'Louveira SP', 225),
('Aparecida GO', 'São Carlos SP', 650),
('Hidrolândia GO', 'Brasília DF', 250),
('São Carlos SP', 'Manutenção em Ribeirão', 150),
('Cravinhos SP', 'Dourados MS', 895),
('Cravinhos SP', 'Hidrolândia GO', 650),
('São Paulo SP', 'Rio de Janeiro RJ', 446),
('Guarulhos SP', 'Araçatuba SP', 532),
('Maringá PR', 'Curitiba PR', 426),
('Cravinhos SP', 'São Paulo SP', 293),
('Duque de Caxias RJ', 'Curitiba PR', 820),
('Campo Grande RJ', 'Curitiba PR', 976),
('São João de Meriti RJ', 'São Paulo SP', 420),
('Curitiba PR', 'Itapema', 235),
('Louveira SP', 'Aparecida GO', 817),
('Hidrolândia GO', 'Louveira SP', 799),
('Curitiba PR', 'Rio de Janeiro RJ', 853),
('São Carlos SP', 'Rio de Janeiro RJ', 641),
('Curitiba PR', 'Itajaí', 211),
('Curitiba PR', 'Cascavel', 600),
('Guarulhos SP', 'São João de Meriti RJ', 539),
('Curitiba PR', 'Louveira SP', 480),
('Curitiba PR', 'Blumenau', 243),
('Hidrolândia GO', 'Ribeirão Preto SP', 564),
('Cascavel PR', 'Guarulhos SP', 942),
('Louveira SP', 'Goiânia', 836),
('Franco da Rocha SP', 'Santana de Parnaíba SP', 50),
('Guarulhos SP', 'Aparecida GO', 898),
('Juiz de Fora MG', 'Guarulhos SP', 462),
('Louveira SP', 'Curitiba PR', 452),
('São Paulo SP', 'Juiz de Fora MG', 489),
('Santana de Parnaíba SP', 'Hidrolândia GO', 851),
('Maringá PR', 'Guarulhos SP', 661),
('Hidrolândia GO', 'São Paulo SP', 868),
('Santana de Parnaíba SP', 'Juiz de Fora MG', 541),
('Louveira SP', 'Goiânia', 836),
('Rio de Janeiro RJ', 'Artur Alvim SP', 429),
('Louveira SP', 'Goiânia GO', 848),
('Santana de Parnaíba SP', 'Campo Grande RJ', 440),
('Goiânia GO', 'Louveira SP', 835),
('São Carlos SP', 'Guarulhos SP', 294),
('Campo Grande RJ', 'São Paulo SP', 407),
('Curitiba PR', 'Criciúma SC', 485),
('Rio de Janeiro RJ', 'São Paulo SP', 429),
('Curitiba PR', 'Duque de Caxias RJ', 850),
('Cravinhos SP', 'Goiânia GO', 658),
('Tatuí SP', 'Santana de Parnaíba SP', 200),
('São Paulo SP', 'São João de Meriti RJ', 400),
('Hidrolândia GO', 'Goiânia GO', 200),
('Curitiba PR', 'Lages SC', 365),
('Cravinhos SP', 'Presidente Prudente SP', 465),
('Aparecida GO', 'Louveira SP', 816),
('Duque de Caxias RJ', 'São Paulo SP', 423),
('Duque de Caxias RJ', 'Guarulhos SP', 408);