-- Script para adicionar coluna id_central à tabela tire_requests
-- Esta coluna é usada para relacionar solicitações locais da Base Campinas com o módulo central de pneus

-- Primeiro, verificar se a tabela existe e criar se não existir
CREATE TABLE IF NOT EXISTS tire_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  base_id INTEGER NOT NULL,
  usuario_id INTEGER,
  quantidade INTEGER NOT NULL,
  marca VARCHAR(100) NOT NULL,
  modelo VARCHAR(100) NOT NULL,
  medida VARCHAR(100) NOT NULL,
  tipo VARCHAR(100) NOT NULL,
  motivo TEXT NOT NULL,
  observacoes TEXT,
  status VARCHAR(50) NOT NULL DEFAULT 'pendente',
  data_solicitacao TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  data_aprovacao TIMESTAMP WITH TIME ZONE,
  aprovador_id INTEGER,
  id_central INTEGER -- Coluna que será adicionada, se não existir
);

-- Verificar se a coluna id_central já existe na tabela
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'tire_requests' AND column_name = 'id_central'
  ) THEN
    -- Adicionar a coluna se não existir
    ALTER TABLE tire_requests ADD COLUMN id_central INTEGER;
    
    -- Adicionar índice para otimizar buscas por id_central
    CREATE INDEX IF NOT EXISTS idx_tire_requests_id_central ON tire_requests(id_central);
    
    -- Registrar alteração no log
    RAISE NOTICE 'Coluna id_central adicionada à tabela tire_requests';
  ELSE
    RAISE NOTICE 'Coluna id_central já existe na tabela tire_requests';
  END IF;
END $$;

-- Verificar se a tabela tem registros
SELECT COUNT(*) FROM tire_requests;